name: review check bot

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

env:
  TZ: "Asia/Tokyo"

jobs:
  readyForTestChecker:
    runs-on: ubuntu-latest
    if: ${{ !(github.event.pull_request.draft == true && contains(github.event.pull_request.labels.*.name, 'stop_ci'))}}
    steps:
      - run: echo this pull request is ready for review by team1
  labeler:
      permissions:
        contents: read
        pull-requests: write
      runs-on: ubuntu-latest
      needs: readyForTestChecker
      steps:
        - uses: actions/labeler@v4
          with:
            repo-token: "${{ secrets.GITHUB_TOKEN }}"
            configuration-path: ".github/config/labeler.yaml"
            sync-labels: true
  commentResult:
    runs-on: ubuntu-latest
    needs: labeler
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            // Get the existing comments.
            const {data: comments} = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.number,
            });
            
            const botComment = comments.find(comment => comment.user.id === 41898282);                                                                  
            const commentBody = `👋 check is done `
            
            if (botComment) {
                await github.rest.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: botComment.id,
                  body: commentBody
                })
               github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['BotReviewed']
              })
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.number,
                body:  commentBody
              })
            }
